# -*- encoding: utf-8 -*-

=begin
#Super API Documentation

#The Super API makes superannuation fund data easily accessible for developers.  Build the future.

The version of the OpenAPI document: 1.0.0
Contact: support@superapi.com.au
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "super-api/version"

Gem::Specification.new do |s|
  s.name        = "super-api"
  s.version     = SuperAPI::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["SuperAPI"]
  s.email       = ["support@superapi.com.au"]
  s.homepage    = "https://github.com/SuperAPIau/ruby-sdk-super-api"
  s.summary     = "Ruby SDK for accessing superannuation data via SuperAPI.com.au"
  s.description = "Ruby SDK for accessing superannuation data via SuperAPI.com.au"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
