=begin
#Super API Documentation

#The Super API makes superannuation fund data easily accessible for developers.  Build the future.

The version of the OpenAPI document: 1.0.0
Contact: support@superapi.com.au
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SuperAPI::FundOptionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FundOptionsApi' do
  before do
    # run before each test
    @api_instance = SuperAPI::FundOptionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FundOptionsApi' do
    it 'should create an instance of FundOptionsApi' do
      expect(@api_instance).to be_instance_of(SuperAPI::FundOptionsApi)
    end
  end

  # unit tests for get_v1_fund_options
  # List of FundOptions for AustralianSuper
  # This endpoint enables developers to retrieve a list of the FundOptions available from AustralianSuper.  FundOptions enable an AustralianSuper member to determine (at a high level) the makeup of their superannuation portfolio.  The FundOptions can be utilised with other endpoints to retrieve additional details related to the FundOption, such as the performance of the portfolio over time.
  # @param [Hash] opts the optional parameters
  # @return [Array<APIEntitiesFundOption>]
  describe 'get_v1_fund_options test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_fund_options_name
  # Details of a FundOption
  # This endpoint enables developers to retrieve the details of a FundOption.
  # @param name Name of the FundOption requested
  # @param [Hash] opts the optional parameters
  # @return [APIEntitiesFundOption]
  describe 'get_v1_fund_options_name test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
