=begin
#Super API Documentation

#The Super API makes superannuation fund data easily accessible for developers.  Build the future.

The version of the OpenAPI document: 1.0.0
Contact: support@superapi.com.au
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SuperAPI::PerformanceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PerformanceApi' do
  before do
    # run before each test
    @api_instance = SuperAPI::PerformanceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PerformanceApi' do
    it 'should create an instance of PerformanceApi' do
      expect(@api_instance).to be_instance_of(SuperAPI::PerformanceApi)
    end
  end

  # unit tests for get_v1_name_annual
  # Annual Performance
  # The annual performance for a FundOption for a given year.
  # @param name 
  # @param year Year of the performance data
  # @param [Hash] opts the optional parameters
  # @return [APIEntitiesAnnualPerformance]
  describe 'get_v1_name_annual test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_name_cumulative
  # Cumulative Performance
  # The cumulative performance from the inception of the FundOption.  This represents the growth over time from the inception date of the FundOption to the requested date.
  # @param name 
  # @param start_date Start date of the desired cumulative period
  # @param end_date End date of the desired cumulative period
  # @param [Hash] opts the optional parameters
  # @return [APIEntitiesCumulativePerformance]
  describe 'get_v1_name_cumulative test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_name_daily
  # Daily Performance
  # The performance for a superannuation FundOption on a specific day.  Not all FundOptions will have a performance on every day, as some FundOptions are not relevant on every day (ie: public holidays, weekends, market closures, etc).  A result of 0 represents no performance.
  # @param name 
  # @param date Date of the performance data
  # @param [Hash] opts the optional parameters
  # @return [APIEntitiesPerformance]
  describe 'get_v1_name_daily test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_name_daily_latest
  # Latest Performance
  # Retrieves the performance for the most recent date, for which performance data exists.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [APIEntitiesPerformance]
  describe 'get_v1_name_daily_latest test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_name_daily_today
  # Today&#39;s Performance
  # Retrieves the performance for today.  This retrieves the same results as the Daily endpoint, but provides a shortcut to retrieve todays performance for a given FundOption.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [APIEntitiesPerformance]
  describe 'get_v1_name_daily_today test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_name_daily_yesterday
  # Yesterday&#39;s Performance
  # Retrieves the performance for yesterday.  This retrieves the same results as the Daily endpoint, but provides a shortcut to retrieve yesterday performance for a given FundOption.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [APIEntitiesPerformance]
  describe 'get_v1_name_daily_yesterday test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
