=begin
#Super API Documentation

#The Super API makes superannuation fund data easily accessible for developers.  Build the future.

The version of the OpenAPI document: 1.0.0
Contact: support@superapi.com.au
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0-SNAPSHOT

=end

# Common files
require 'super-api/api_client'
require 'super-api/api_error'
require 'super-api/version'
require 'super-api/configuration'

# Models
require 'super-api/models/api_entities_annual_performance'
require 'super-api/models/api_entities_cumulative_performance'
require 'super-api/models/api_entities_fund_option'
require 'super-api/models/api_entities_performance'

# APIs
require 'super-api/api/fund_options_api'
require 'super-api/api/performance_api'

module SuperAPI
  class << self
    # Customize default settings for the SDK using block.
    #   SuperAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
