=begin
#Super API Documentation

#The Super API makes superannuation fund data easily accessible for developers.  Build the future.

The version of the OpenAPI document: 1.0.0
Contact: support@superapi.com.au
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0-SNAPSHOT

=end

module SuperAPI
  VERSION = '1.0.0'
end
